### ISSUE TITLE
Fatal error during installation

### ISSUE THREAD

**Issue by r23** [MozillaReality/hello-webxr#82]
Hello

unfortunately I get an error message during the installation.

8<- debug.log
7950 silly saveTree   └── gl-matrix@2.8.1
7951 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
7952 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/public_html/hello-webxr/node_modules/.staging/fsevents-a143263e/node_modules/abbrev' -> '/public_html/hello-webxr/node_modules/.staging/abbrev-c1456492'
7953 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
7953 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
7954 verbose stack Error: Command failed: git clone --depth=1 -q -b master git://github.com/mozillareality/ecsy.git /root/.npm/_cacache/tmp/git-clone-743933a0
7954 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-743933a0': Permission denied
7954 verbose stack
7954 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
7954 verbose stack     at ChildProcess.emit (events.js:198:13)
7954 verbose stack     at maybeClose (internal/child_process.js:982:16)
7954 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
7954 verbose stack     at Socket.emit (events.js:198:13)
7954 verbose stack     at Pipe._handle.close (net.js:607:12)
7955 verbose cwd /public_html/hello-webxr
7956 verbose Linux 4.15.0-50-generic
7957 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
7958 verbose node v10.19.0
7959 verbose npm  v6.13.4
7960 error code 128
7961 error Command failed: git clone --depth=1 -q -b master git://github.com/mozillareality/ecsy.git /root/.npm/_cacache/tmp/git-clone-743933a0
7961 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-743933a0': Permission denied
7962 verbose exit [ 1, true ]

8<--

The directory is available
/root/.npm/_cacache/tmp/

i am happy to receive suggestions

Kind regards,

Ralf

**Comment by r23** [comment]
A recommended first step is to use the latest npm:

npm install -g npm
